  spring:
    jpa:
      database: POSTGRESQL
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      url: jdbc:postgresql://192.168.56.25:5432/emenu
      username: levelup
      password: '#=levelup=#=2022=#'
      driverClassName: org.postgresql.Driver

  server:
    port: 9090